name: e2e

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

permissions:
  contents: read

env:
  FLUX_MODULE_URL: "oci://localhost:5000/flux-aio"
  FLUX_SYNC_MODULE_URL: "oci://localhost:5000/flux-git-sync"
  FLUX_OCI_MODULE_URL: "oci://localhost:5000/flux-oci-sync"
  FLUX_TENANT_MODULE_URL: "oci://localhost:5000/flux-tenant"
  FLUX_HR_MODULE_URL: "oci://localhost:5000/flux-helm-release"
  FLUX_MODULE_VERSION: "0.0.0-devel"

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@74ab9cc2fbee3459505706f5fb7c2742ecffbf5d # v0.33.0
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@889be9d6cc8afa8ed639e1e1ba4ab678e3b38d8c # v2.9.4
      - name: Check CUE formatting
        run: make fmt-check
      - name: Vet modules
        run: make vet
      - name: Create cluster without CNI
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          cluster_name: kind
          config: ./test/cluster/kind.yaml
          node_image: ghcr.io/fluxcd/kindest/node:v1.35.1-amd64
          wait: 0s
      - name: Push modules
        run: |
          timoni mod push ./modules/flux-aio ${FLUX_MODULE_URL} -v ${FLUX_MODULE_VERSION} --resolve-symlinks
          timoni mod push ./modules/flux-git-sync ${FLUX_SYNC_MODULE_URL} -v ${FLUX_MODULE_VERSION} --resolve-symlinks
          timoni mod push ./modules/flux-oci-sync ${FLUX_OCI_MODULE_URL} -v ${FLUX_MODULE_VERSION} --resolve-symlinks
          timoni mod push ./modules/flux-tenant ${FLUX_TENANT_MODULE_URL} -v ${FLUX_MODULE_VERSION} --resolve-symlinks
          timoni mod push ./modules/flux-helm-release ${FLUX_HR_MODULE_URL} -v ${FLUX_MODULE_VERSION} --resolve-symlinks
      - name: Apply flux-aio bundle
        run: |
          PR_NUMBER=${{ github.event.number }}
          if [ -z "$PR_NUMBER" ]
          then
            export FLUX_SYNC_REF=${GITHUB_REF}
          else
            export FLUX_SYNC_REF="refs/pull/${PR_NUMBER}/head"
          fi
          
          timoni bundle apply -f bundles/flux-aio.cue --runtime-from-env
      - name: Verify Flux installation
        run: flux check
      - name: Verify CoreDNS availability
        run: kubectl -n kube-system rollout status deploy/coredns --timeout=5m
      - name: Apply flux-tenants bundle
        run: |
          timoni bundle apply -f bundles/flux-tenants.cue --runtime-from-env
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n kube-system get pods
          kubectl -n flux-system get pods
          kubectl -n flux-system get gitrepository -oyaml
          kubectl -n flux-system get kustomization -oyaml
          kubectl -n flux-system get helmchart -oyaml
          kubectl -n flux-system get helmrelease -oyaml
          flux get all --all-namespaces
