name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@74ab9cc2fbee3459505706f5fb7c2742ecffbf5d # v0.33.0
      - name: Check CUE formatting
        run: make fmt-check
      - name: Vet modules
        run: make vet
