name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install tools
        run: make tools
      - name: Run CUE format
        run: |
          make fmt
          if [[ $(git diff --stat) != '' ]]; then
            echo 'run "make fmt" and commit changes'
            exit 1
          fi
      - name: Vet modules
        run: make vet
